### ISSUE TITLE
Inconsistent CLI syntax for taxa

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/phyltr#25]
I just came across something I consider inconsistent: The `grep` command has the following syntax:
```
phyltr grep [taxa] [<options>] [<files>]
```
But this only works because either `taxa` must be specified or an option must be present. Otherwise, the first argument passed as `files` will be assumed to specify `taxa`, which probably fails with "Must specify more than one taxon" (which does not make too much sense) - unless there's a comma in the filename at which point it may get totally weird.

I'd propose to make `taxa` an explicit option, too. This might seem a bit weird, because then we'd **require** at least one **optional argument** - but we might remedy this by allowing `self.taxa` to be empty - which will result in no trees being selected.

**Comment by lmaurits** [comment]
Hmm.  This situation isn't unique to `grep`, is it?  I think `prune` and `subtree`, at least, have very similar syntax...

**Comment by xrotwang** [comment]
Yes, that's the case for multiple commands (and also for different arguments).

**Comment by xrotwang** [comment]
From the perspective of uniformity of subcommands, I'd say there's no way around making all non-files arguments options. Of course this would be a bit nicer if all commands had sensible default (in the absence of any options) behaviour ...

**Comment by xrotwang** [comment]
Regarding default behaviour - wouldn't it be acceptable, if commands like `grep` or `prune` would default to identity, i.e. simply pass trees through?

I also just looked up the behaviour of csvkit's `csvgrep`. They probably also had to make the decisions and opted for making **all** non-input-file arguments options, and react to no options with
```bash
$ csvgrep ~/test.py 
usage: csvgrep [-h] [-d DELIMITER] [-t] [-q QUOTECHAR] [-u {0,1,2,3}] [-b]
               [-p ESCAPECHAR] [-z FIELD_SIZE_LIMIT] [-e ENCODING] [-S] [-H]
               [-K SKIP_LINES] [-v] [-l] [--zero] [-V] [-n] [-c COLUMNS]
               [-m PATTERN] [-r REGEX] [-f MATCHFILE] [-i] [-a]
               [FILE]
csvgrep: error: You must specify at least one column to search using the -c option.
```

**Comment by lmaurits** [comment]
I think defaulting to identity makes a lot of sense, if we do want to have non-error behaviour in the case of empty options.

I understand how the current behaviour is problematic.  I guess the thing which makes me less than enthusiastic about this solution is that in 99% of my actual real-world usage, all phyltr commands other than `cat` are reading from `stdin`and so the `files` argument is simply never there, whereas the optional `taxa` command always is.  So we'd be making the normal, everyday usage more verbose and asking users to remember more syntax, to avoid a problem which almost never comes up.  I wonder if making `files` an explicit argument is a better solution...but then, for consistency, `cat` would need to act that way too, and that makes the first component in just about every pipeline more verbose...

Aside: a long-term plan with `grep` was always to support giving it not just a list of taxa, but an actual chunk of Newick, so you can condition on particular clade structure.

**Comment by xrotwang** [comment]
Hm, okay, `phyltr cat` is a bit of an outlier here. But maybe renaming it to `phyltr sample` would do the trick? Maybe giving it a `--from-nexus` option? Then you'd start your pipeline with the "real" `cat`:
```
cat [files] | phyltr sample --from-nexus | ...
```

**Comment by xrotwang** [comment]
Coming back to the "remove the `files` arguments" idea: This would also open the way for commands to specify repeatable arguments. I.e. no more "must be a comma-separated list of ..." syntax, but instead
```
phyltr grep taxon1 taxon2
```

**Comment by lmaurits** [comment]
Aaaah, now *that's* an appealing thing!

Coming back to it today, I don't think that it's really a serious problem for `cat` to be inconsistent in not requiring an explicit `--files`.  It's the only command whose primary function involves reading from a file, so it's natural for it to a simpler syntax to handle that.

If we did that, rather than requiring an explicit `--taxa` for all other functions, then typical real-world pipelines wouldn't change in length/complexity at all, and in fact with your suggestion above, typical uses would become *better* looking not worse, as we could ditch the comma-separated lists.

**Comment by xrotwang** [comment]
Also, `cat` would specify it needs a `files` argument explicitly, just as `grep` would with `taxa`. So it may not be 100% consistent, but is certainly transparent and discoverable.

**Comment by xrotwang** [comment]
See https://docs.python.org/3/library/argparse.html#example

**Comment by xrotwang** [comment]
I think I like this:
https://github.com/xrotwang/phyltr/commit/361f09d2cfb5ecf1270b5d8c805217c7675fb557

Help thanks to `argparse`:
```
$ phyltr cat --help
usage: phyltr cat [-h] [-b BURNIN] [-s SUBSAMPLE] [--no-annotations]
                  [--topology-only]
                  FILE [FILE ...]

Extract phylogenetic trees from the specified files and print them as a
treestream. The trees may contain trees formatted as a phyltr treestream or a
NEXUS file.

positional arguments:
  FILE

optional arguments:
  -h, --help            show this help message and exit
  -b BURNIN, --burnin BURNIN
                        Percentage of trees from each file to discard as 'burn
                        in'. Default is 0, i.e. no burn in. (default: 0)
  -s SUBSAMPLE, --subsample SUBSAMPLE
                        Frequency at which to subsample trees, i.e. '-s 10'
                        will include only every 10th tree in the treestream.
                        Default is 1. (default: 1)
  --no-annotations      Do not include any annotations on nodes (e.g. clock
                        rates, phylogeographic locations, etc.), print only
                        standard metadata (i.e. branch lengths and clade
                        supports) (default: False)
  --topology-only       Print very clean trees with only the leaf names and
                        branching structure included, removing branch lengths,
                        clade supports and any other annotations. Stronger
                        than, and overrides, --no-annotations. (default:
                        False)
```

**Comment by lmaurits** [comment]
This is the nicest solution I think we're likely to come up with for the problem you pointed out at the start of this Issue, so let's go for it!

**Comment by xrotwang** [comment]
That's another annoyance (at least for developers - maybe it's a service for end users) of the `develop` branch model: Closed issues (in `develop`) will stay open until merged into `master`.
