### ISSUE TITLE
Implement --no-annotations

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/phyltr#6]
The `cat` command parses the option `--no-annotations`, but ignores it.

A way to scrub annotations would be nice, because eg. Beastling does not like the NHX trees coming out otherwise.

**Comment by lmaurits** [comment]
This is news to me, I am pretty sure I have successfully used `--no-annotations` previously to strip out NHX stuff to make other tools happy.  Let me see if I have forgotten to commit something...

**Comment by Anaphory** [comment]
It's not here in `develop`. My implementation would be a `class UnannaotatedNewickFormatter (NewickFormatter)` and in `Cat.__init__`

        if not annotations:
            self.sink = UnannotatedNewickFormatter

I'm curious to see yours.

**Comment by lmaurits** [comment]
Isn't `NewickFormatter` [initialised with an argument](https://github.com/lmaurits/phyltr/blob/f2a4481c7f1db0053976b4608146f56751c93e3d/phyltr/commands/cat.py#L53) indicating whether or not to use annotations?

**Comment by Anaphory** [comment]
Ah. Not in `master`, which I cloned, nor in the way I expected in `develop`, which I looked at above.

But yes, it's there, and why did I clone the master branch and not the development branch in the first place…

**Comment by lmaurits** [comment]
Ah, you're right, it's not in master yet.  Maybe I should cut a new relesae.  I'm going to submit an abstract on phyltr to the Tuebingen meeting today or tomorrow, so I should probably have a recent release to be able to refer to.

**Comment by Anaphory** [comment]
(It's fine in `develop`)
